# Generated by Django 5.1 on 2024-09-24 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def seed_data(apps, schema_editor):
    # Get the models from the historical version (instead of importing them directly)
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('courses', 'Profile')
    Category = apps.get_model('courses', 'Category')
    Course = apps.get_model('courses', 'Course')

    # Define roles
    ROLE_STUDENT = 1
    ROLE_TUTOR = 2

    # Create users (students and tutors)
    student = User.objects.create_user(username='student', password='student', first_name='Student', last_name='Zero', email='student@example.com')
    student1 = User.objects.create_user(username='student1', password='student1', first_name='Student', last_name='One', email='student1@example.com')
    student2 = User.objects.create_user(username='student2', password='student2', first_name='Student', last_name='Two', email='student2@example.com')
    student3 = User.objects.create_user(username='student3', password='student3', first_name='Student', last_name='Three', email='student3@example.com')

    tutor = User.objects.create_user(username='tutor', password='tutor', first_name='Tutor', last_name='Zero', email='tutor@example.com')
    tutor1 = User.objects.create_user(username='tutor1', password='tutor1', first_name='Tutor', last_name='One', email='tutor1@example.com')
    tutor2 = User.objects.create_user(username='tutor2', password='tutor2', first_name='Tutor', last_name='Two', email='tutor2@example.com')
    tutor3 = User.objects.create_user(username='tutor3', password='tutor3', first_name='Tutor', last_name='Three', email='tutor3@example.com')

    # Assign roles to profiles
    Profile.objects.create(user=student, roles=ROLE_STUDENT)
    Profile.objects.create(user=student1, roles=ROLE_STUDENT)
    Profile.objects.create(user=student2, roles=ROLE_STUDENT)
    Profile.objects.create(user=student3, roles=ROLE_STUDENT)

    Profile.objects.create(user=tutor, roles=ROLE_TUTOR)
    Profile.objects.create(user=tutor1, roles=ROLE_TUTOR)
    Profile.objects.create(user=tutor2, roles=ROLE_TUTOR)
    Profile.objects.create(user=tutor3, roles=ROLE_TUTOR)

    # Create categories
    programming_category, _ = Category.objects.get_or_create(
        name='Programming',
        defaults={'description': 'Courses related to programming and development.'}
    )
    mathematics_category, _ = Category.objects.get_or_create(
        name='Mathematics',
        defaults={'description': 'Courses related to mathematics and problem-solving.'}
    )
    science_category, _ = Category.objects.get_or_create(
        name='Science',
        defaults={'description': 'Courses related to various scientific disciplines.'}
    )

    # Create courses and assign them to tutors
    Course.objects.get_or_create(
        title='Python for Beginners',
        category=programming_category,
        defaults={'description': 'An introductory course to learn Python programming.', 'tutor': Profile.objects.get(user=tutor1)}
    )
    Course.objects.get_or_create(
        title='Advanced Calculus',
        category=mathematics_category,
        defaults={'description': 'A deep dive into calculus for advanced learners.', 'tutor': Profile.objects.get(user=tutor2)}
    )
    Course.objects.get_or_create(
        title='Physics 101',
        category=science_category,
        defaults={'description': 'An introduction to the basics of physics.', 'tutor': Profile.objects.get(user=tutor3)}
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taught_courses', to='courses.profile')),
            ],
        ),

        migrations.RunPython(seed_data),
    ]
