name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t mirotivo/tutorials:latest .
        docker push mirotivo/tutorials:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_SERVER_IP }}
        username: ${{ secrets.AZURE_SERVER_USERNAME }}
        key: ${{ secrets.AZURE_SERVER_PEM }}
        script: |
          docker pull mirotivo/tutorials:latest
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 8080:80 mirotivo/tutorials:latest
